# Generated by Django 3.0.5 on 2020-04-15 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ingrediente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(default='', max_length=100)),
                ('Precio', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disponible', models.BooleanField(default=True)),
                ('Cantidad', models.IntegerField(default=1)),
                ('Dimensional', models.CharField(max_length=50)),
                ('Ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ingrediente', to='Ingrediente.Ingrediente')),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Menu', to='Menu.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='Ingredientes',
            field=models.ManyToManyField(through='Menu.Menu_Ingrediente', to='Ingrediente.Ingrediente'),
        ),
    ]
